const GALLERY_PHOTOS = [
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/191.jpg",       caption: "ನೀನು ನನ್ನ ಜೀವನದ ಫೇವರಿಟ್ ಪರ್ಸನ್ ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p111.png",     caption: "You came as a friend, stayed as family ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p222.png",     caption: "ರಕ್ತದ ಸಂಬಂಧ ಅಲ್ಲ… ಹೃದಯದ ಸಂಬಂಧ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p333.png",     caption: "Not blood related, still soul related 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p444.png",     caption: "ನನ್ನ ಫೇವರಿಟ್ ಪರ್ಸನ್ — ನೀನು 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p555.png",     caption: "My favorite person, my safe place 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p666.png",     caption: "ನೀನು ಇದ್ದರೆ ಸಾಕು ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p777.png",     caption: "She’s my akka by heart, not by birth ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p888.png",     caption: "ನನ್ನ ಸಂತೋಷಕ್ಕೆ ಕಾರಣ ನೀನು ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p999.png",     caption: "Some bonds are written by fate ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p11111.png",   caption: "ನನ್ನ ಜಗತ್ತಿನ ಸ್ಪೆಷಲ್ ವ್ಯಕ್ತಿ ನೀನು 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p22222.png",   caption: "From 2023 strangers to forever siblings 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p101010.png",  caption: "ಅಕ್ಕ ಅಲ್ಲ… ನನ್ನ ಹ್ಯಾಪಿನೆಸ್ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p333333.png",   caption: "I found a sister where I least expected 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/13333.png",   caption: "ನೀನು ಬಂದ್ಮೇಲೆ ಜೀವನ ಚೆನ್ನಾಯಿತು 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/6.JPG",   caption: "I found a sister where I least expected 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/7.JPG",   caption: "Forever ನಿನ್ನ ತಮ್ಮ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/8.JPG",   caption: "My happiness has a name — Lacchi 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/9.JPG",   caption: "ನಿನ್ನ ಜಾಗ ಯಾರಿಗೂ ಇಲ್ಲ 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/10.JPG",   caption: "She treats me like her own brother 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/11.JPG",   caption: "ನೀನು ನನ್ನ comfort person 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/12.JPG",   caption: "The best bonds happen unexpectedly ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/13.JPG",   caption: "ಮಾತು ಬಿಡಬೇಡ ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/14.jpg",   caption: "You understand my silence too 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/15.jpg",   caption: "ನನ್ನ ನಗುವಿನ ಕಾರಣ ನೀನು ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/16.jpg",   caption: "One person, unlimited care ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/17.jpg",   caption: "ನೀನು ಸಿಕ್ಕಿದ್ದು ನನ್ನ luck 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/18.jpg",   caption: "Sister by bond, forever by heart 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/19.jpg",   caption: "ನನ್ನ ಜೀವನದ ಬೆಸ್ಟ್ ಗಿಫ್ಟ್ — ನೀನು ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/20.jpg",   caption: "Please stay till my last breath 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/21.jpg",   caption: "ನೀನು ನನ್ನ safe place 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/22.jpg",   caption: "You fixed parts of me you never broke 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/23.jpg",   caption: "ಅಕ್ಕ by heart ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/82.jpg",   caption: "My comfort person ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/83.jpg",   caption: "ನಿನ್ನ ಜೊತೆನೇ ಮನಸ್ಸಿಗೆ ಶಾಂತಿ 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/26.jpg",   caption: "I trust you more than anyone 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/27.jpg",   caption: "ನನ್ನ ಹೃದಯಕ್ಕೆ ಹತ್ತಿರದ ವ್ಯಕ್ತಿ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/28.jpg",   caption: "Life got better after you entered it ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/29.jpg",   caption: "ನೀನು ನನ್ನ ಲೋಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/164.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಎರಡನೇ ಅಮ್ಮ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/31.jpg",   caption: "ನನ್ನ smile ಹಿಂದೆ ನೀನು 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/32.jpg",   caption: "Not everyone gets a bond like this 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/33.jpg",   caption: "ನನ್ನ peace, ನನ್ನ akka 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/34.jpg",   caption: "If I made mistakes, scold me… but don’t leave me. 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/35.jpg",   caption: "ನಿನ್ನ ಜಾಗ ಶಾಶ್ವತ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/36.jpg",   caption: "“You’re the reason my smile came back.” ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/37.jpg",   caption: "ನೀನು ಇದ್ದರೆ ಎಲ್ಲ ಚೆನ್ನಾಗಿದೆ 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/38.png",   caption: "“After meeting you, life felt lighter.” 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/39.jpg",   caption: "ನನ್ನ favorite notification — ನೀನು 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/40.jpg",   caption: "“No matter who comes, your place stays special.” ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/41.jpg",   caption: "ನೀನು ನನ್ನ happiness ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/42.jpg",   caption: "“You are my favorite chapter.” 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/43.jpg",   caption: "ನನ್ನ ಮನಸ್ಸಿನ ಹತ್ತಿರ ನೀನು 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/44.jpg",   caption: "You’re not part of my life, you are my life 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/45.jpg",   caption: "ಅಕ್ಕ ಅಂತ ಕರೆಯೋದು ನನ್ನ luck 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/47.jpg",   caption: "Akka by choice, family by heart ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/48.jpg",   caption: "ನನ್ನ ದಿನದ best part — ನೀನು ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/50.jpg",   caption: "Some people become home 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/51.jpg",   caption: "ನೀನು ಮಾತಾಡಿದ್ರೆ ಸಾಕು 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/52.jpg",   caption: "You entered my life and changed everything ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/53.jpg",   caption: "ನಿನ್ನ care ತುಂಬಾ special ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/54.jpg",   caption: "My heart feels safe with you 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/55.jpg",   caption: "ನೀನು ಬೇರೆ level akka 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/56.jpg",   caption: "You’re my peace in a noisy world 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/57.jpg",   caption: "ನನ್ನ heart ಗೆ close ಇರುವವಳು ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/58.jpg",   caption: "I didn’t expect you, but I needed you ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/59.jpg",   caption: "ನೀನು ಸಿಕ್ಕಿದ್ದು blessing 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/60.jpg",   caption: "Lucky to have a sister like you 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/61.jpg",   caption: "ನನ್ನ favorite chapter — ನೀನು 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/62.jpg",   caption: "One bond, countless memories ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/63.jpg",   caption: "ಮಾತು ಬಿಡಬೇಡ ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/64.jpg",   caption: "My favorite notification is yours 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/65.jpg",   caption: "ನೀನು ಇಲ್ಲ ಅಂದ್ರೆ ಏನೋ missing 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/66.jpg",   caption: "You are my daily happiness ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/67.jpg",   caption: "Forever ನೀನೇ special ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/68.jpg",   caption: "My person. My akka. My comfort 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/69.jpg",   caption: "ನನ್ನ ಟ್ರಸ್ಟ್ ಶುರು ಆಗೋದು ನಿನ್ನಿಂದ 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/70.jpg",   caption: "You’re my strongest support system 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/71.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಜೀವನ ಅರ್ಧ ಸಮಸ್ಯೆ ಕಡಿಮೆ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/72.jpg",   caption: "The best thing 2024 gave me — you ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/73.jpg",   caption: "ಅಕ್ಕನ ಪ್ರೀತಿ ಬೇರೆ level ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/74.jpg",   caption: "My bond with you > everything ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/75.jpg",   caption: "ಜಗಳ ಜಾಸ್ತಿ… ಪ್ರೀತಿ ಇನ್ನೂ ಜಾಸ್ತಿ 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/76.jpg",   caption: "I smile differently because of you 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/77.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಮನೆಗೆ ಬೇರೆ ಖುಷಿ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/78.jpg",   caption: "You’re my permanent favorite ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/79.jpg",   caption: "ನನ್ನ ಮೊದಲ best friend — ನನ್ನ ಅಕ್ಕ 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/80.jpg",   caption: "One call from you fixes my mood 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/81.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ care + love + support ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/82.jpg",   caption: "You’re my happy place 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/83.jpg",   caption: "ನನ್ನ strength — ನನ್ನ ಅಕ್ಕ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/84.jpg",   caption: "Thank you for treating me like your own brother ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/85.jpg",   caption: "ಅಕ್ಕನ ಬೈಗುಳದಲ್ಲೂ ಪ್ರೀತಿ ಇರುತ್ತೆ 😄❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/86.jpg",   caption: "I don’t want many people, I just want you around 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/87.jpg",   caption: "ಎಲ್ಲರಿಗೂ ಅಕ್ಕ ಇರುತ್ತಾರೆ, ನನ್ನಂಥ ಅಕ್ಕ ಎಲ್ಲರಿಗೂ ಇರಲ್ಲ 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/88.jpg",   caption: "You became special without even trying ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/89.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಚಿಕ್ಕ ಚಿಕ್ಕ ಸಂತೋಷಗಳ ದೊಡ್ಡ ಕಾರಣ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/90.jpg",   caption: "Some bonds don’t need explanations 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/91.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಯಾವ tension ಕೂಡ tension ಅನಿಸಲ್ಲ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/92.jpg",   caption: "Sister by heart, not by blood ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/93.jpg",   caption: "ಸಿಸ್ಟರ್ ಅಲ್ಲ… ನನ್ನ superhero ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/94.jpg",   caption: "Forever my Angel ◈" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/95.jpg",   caption: "ಅಕ್ಕ ಜೊತೆ ಜಗಳ ದಿನವೂ… ಮಾತು ಬಿಡೋದು never 😄" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/96.jpg",   caption: "Forever my Pretty Angel Akka 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/97.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಮನೆಯ peace 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/98.jpg",   caption: "You’re the chapter I never want to end 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/99.jpg",   caption: "ಜೀವನದಲ್ಲಿ ಬೆಸ್ಟ್ gift — ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/100.jpg",   caption: "Your care means the world to me ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/101.jpg",   caption: "ಅಕ್ಕನ ಪ್ರೀತಿ explain ಮಾಡೋಕೆ words ಸಾಲಲ್ಲ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/102.jpg",   caption: "My trust starts with you 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/103.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಮನಸ್ಸಿಗೆ ಧೈರ್ಯ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/104.jpg",   caption: "You understand me without words 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/105.jpg",   caption: "Forever my favorite akka 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/106.jpg",   caption: "Stay with me forever, akka ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/107.jpg",   caption: "ಅಕ್ಕ = love in another form ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/108.jpg",   caption: "Every memory with you is precious ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/109.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಧೈರ್ಯ ತಾನಾಗೇ ಬರುತ್ತೆ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/110.jpg",   caption: "You made life brighter 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/111.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಪ್ರೀತಿಯ ಮತ್ತೊಂದು ಹೆಸರು 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/112.jpg",   caption: "My comfort zone has your name ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/113.jpg",   caption: "ಅಕ್ಕನ ಕಾಳಜಿ ಯಾವಾಗಲೂ ಸ್ಪೆಷಲ್ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/114.jpg",   caption: "Even bad days feel lighter with you 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/115.jpg",   caption: "ಅಕ್ಕ ಜೊತೆ ಜಗಳ common… ಪ್ರೀತಿ permanent 😄❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/116.jpg",   caption: "My favorite human, always 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/117.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಜೀವನ ಸ್ವಲ್ಪ easy ಆಗುತ್ತೆ 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/118.jpg",   caption: "Beat me, scold me… but don’t leave me akka 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/119.jpg",   caption: "ಅಕ್ಕನ ಪ್ರೀತಿ silent ಆಗಿರುತ್ತೆ… ಆದ್ರೆ real ಆಗಿರುತ್ತೆ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/120.jpg",   caption: "Stay with me till my last breath ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/121.jpg",   caption: "ನನ್ನ secret keeper — ನನ್ನ ಅಕ್ಕ 🤫❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/122.jpg",   caption: "Evan yavanu idhella heltidane antha andkobeda 😁" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/123.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಯಾವಾಗಲೂ side ನಿಲ್ಲೋ ವ್ಯಕ್ತಿ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/124.jpg",   caption: "I trust you more than anyone else 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/125.jpg",   caption: "ಮನೆಯ ನಿಜವಾದ support system — ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/126.jpg",   caption: "After meeting you, I started smiling more ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/127.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಒಂಟಿತನ ಕಡಿಮೆ ಆಗುತ್ತೆ 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/128.jpg",   caption: "You came into my life and healed things silently 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/129.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಯಾವಾಗಲೂ caring mode ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/130.jpg",   caption: "No replacement. No comparison. Only you ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/131.jpg",   caption: "ಅಕ್ಕನ ಜೊತೆ memories ಯಾವಾಗಲೂ special 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/132.jpg",   caption: "You’re not a habit, you’re a blessing ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/133.jpg",   caption: "ಒಂದು ಅಕ್ಕ ಇದ್ದರೆ ಸಾಕು, ಜೀವನ colorfull ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/134.jpg",   caption: "Forever your little brother 🤗" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/135.jpg",   caption: "ಅಕ್ಕನ love ಬೇರೆ level ✨" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/136.jpg",   caption: "My world became better after you 🌍❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/137.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಮನೆಯ vibe ಬೇರೆ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/138.jpg",   caption: "An elder sister is a little bit of childhood that never leaves us. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/139.jpg",   caption: "ನನ್ನ ಮೊದಲ teacher — ನನ್ನ ಅಕ್ಕ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/140.jpg",   caption: "My akka: part sister, part best friend, part second mom. 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/141.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ half friend, half mother ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/142.jpg",   caption: "Behind every strong sibling bond is an amazing elder sister. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/143.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಯಾವಾಗಲೂ backup ಇರುತ್ತೆ 😄" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/144.jpg",   caption: "An akka’s care hits differently. 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/145.jpg",   caption: "ನನ್ನ biggest supporter — ನನ್ನ ಅಕ್ಕ ❤️"},
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/146.jpg",   caption: "No one supports like an elder sister. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/147.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ forever safe place 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/148.jpg",   caption: "A sister’s love stays, even when words don’t. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/149.jpg",   caption: "ಅಕ್ಕನ smile ನೋಡಿದ್ರೆ ದಿನ ಚೆನ್ನಾಗುತ್ತೆ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/150.jpg",   caption: "Akka — my forever safe place. 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/151.jpg",   caption: "ಸಣ್ಣ ಜಗಳ, ದೊಡ್ಡ ಪ್ರೀತಿ — ಅಕ್ಕ ಜೊತೆ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/152.jpg",   caption: "An elder sister is life’s first protector. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/153.jpg",   caption: "ಅಕ್ಕನ ಬೈಗುಳವೂ caring version 😄❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/154.jpg",   caption: "An elder sister is the first person who protects you without being asked. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/155.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಮನೆಗೆ extra happiness ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/156.jpg",   caption: "A sister may annoy you daily, but she’ll still stand by you forever. 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/157.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ life ಗೆ balance ಇರುತ್ತೆ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/158.jpg",   caption: "Big sisters don’t let you fall alone. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/159.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ forever support ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/160.jpg",   caption: "A sister’s place can never be replaced. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/161.jpg",   caption: "ಅಕ್ಕನ ಜೊತೆ bond ಬೇರೆ level ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/162.jpg",   caption: "Blessed with the best akka. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/163.jpg",   caption: "ಜಗಳ ಮಾಡ್ತೀವಿ… ಆದ್ರೆ ಇರೋದು ಜೊತೆಯಲ್ಲೇ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/164.jpg",   caption: "Life feels safer when you have an akka beside you. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/165.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ tension ಅರ್ಧ ಆಗುತ್ತೆ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/166.jpg",   caption: "Akka, life feels better with you in it. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/167.jpg",   caption: "ನನ್ನ happiness‌ನ ಒಂದು ಭಾಗ — ಅಕ್ಕ 🤍"},
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/168.jpg",   caption: "You’re not just my sister, you’re my comfort person. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/169.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ trust ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/170.jpg",   caption: "No matter what happens, your place in my life will always stay special. 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/171.jpg",   caption: "ನನ್ನ life partner ಅಲ್ಲ… life supporter — ಅಕ್ಕ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/172.jpg",   caption: "Akka, thank you for always being there for me. 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/173.jpg",   caption: "ಅಕ್ಕ ಜೊತೆ ಇರುವ memories priceless ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/174.jpg",   caption: "You make my worst days feel a little easier. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/175.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ silent strength 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/176.png",   caption: "I’m lucky that life gave me a sister like you. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/177.png",   caption: "ನನ್ನ smileಗೆ ಕಾರಣಗಳಲ್ಲಿ ಒಬ್ಬಳು — ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/178.png",   caption: "You understand me in ways I can’t explain. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/179.png",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಯಾವಾಗಲೂ home feeling 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/180.png",   caption: "Akka, your care means more than you know. 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/181.png",   caption: "ಅಕ್ಕನ care ಯಾವಾಗಲೂ extra ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/182.png",   caption: "You’re my favorite person to annoy and my favorite person to trust. 😄❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/183.png",   caption: "ನನ್ನ biggest blessing — ಅಕ್ಕ 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/184.png",   caption: "I don’t need many people; having you is enough. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/185.png",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ದಿನದ peace ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/186.png",   caption: "Akka, your presence itself gives me peace. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/187.png",   caption: "ಒಂದು ಅಕ್ಕ ಸಾಕು… life happy ಆಗೋಕೆ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/188.png",   caption: "No replacement, no comparison — only you. 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/189.png",   caption: "ಅಕ್ಕ ಜೊತೆಗಿನ bond explain ಮಾಡೋಕೆ words ಸಾಲಲ್ಲ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/190.png",   caption: "Whatever happens, stay with me forever, akka. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p2.png",   caption: "Forever grateful for my akka 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/192.jpg",   caption: "You came into my life and made it brighter. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/195.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಜೀವನಕ್ಕೆ strength ಬರುತ್ತೆ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/196.jpg",   caption: "My happiness has your name in it, akka. 🫶" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/197.jpg",   caption: "ಅಕ್ಕ = love + care + madness 😄❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/198.jpg",   caption: "You’re not my sister by blood, but by heart. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/1.png",   caption: "ಎಲ್ಲರಿಗೂ sister ಇರುತ್ತಾರೆ… ನನ್ನದು akka ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/2.png",   caption: "You’ll always have a special place in my life. 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/3.png",   caption: "ಅಕ್ಕನ ಸ್ಥಾನ ಯಾರೂ ತುಂಬೋಕಾಗಲ್ಲ 🥹" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/4.webp",   caption: "Forever your little brother, akka. ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/5.png",   caption: "ನನ್ನ favorite person — ಅಕ್ಕ ❤️" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p2.png",   caption: "I’m lucky that life gave me a sister like you. 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p111.png",   caption: "ಅಕ್ಕ ಇದ್ದರೆ life ಸ್ವಲ್ಪ beautiful 🤍" },
  { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/p222.png",   caption: "You’re my favorite person to annoy and my favorite person to trust. 😄❤️" },

  // ✏️ Just keep adding lines below — no limit!
  // { src: "https://github.com/rahuldevc23is-cmyk/first-project/releases/download/v1.0.0/newphoto.png", caption: "Your caption here" },
];