const GALLERY_PHOTOS = [
  { src: "photos/191.jpg",       caption: "ನೀನು ನನ್ನ ಜೀವನದ ಫೇವರಿಟ್ ಪರ್ಸನ್ ಅಕ್ಕ ❤️" },
  { src: "photos/p111.png",     caption: "You came as a friend, stayed as family ❤️" },
  { src: "photos/p222.png",     caption: "ರಕ್ತದ ಸಂಬಂಧ ಅಲ್ಲ… ಹೃದಯದ ಸಂಬಂಧ ❤️" },
  { src: "photos/p333.png",     caption: "Not blood related, still soul related 🥹" },
  { src: "photos/p444.png",     caption: "ನನ್ನ ಫೇವರಿಟ್ ಪರ್ಸನ್ — ನೀನು 🥹" },
  { src: "photos/p555.png",     caption: "My favorite person, my safe place 🤗" },
  { src: "photos/p666.png",     caption: "ನೀನು ಇದ್ದರೆ ಸಾಕು ಅಕ್ಕ ❤️" },
  { src: "photos/p777.png",     caption: "She’s my akka by heart, not by birth ❤️" },
  { src: "photos/p888.png",     caption: "ನನ್ನ ಸಂತೋಷಕ್ಕೆ ಕಾರಣ ನೀನು ✨" },
  { src: "photos/p999.png",     caption: "Some bonds are written by fate ✨" },
  { src: "photos/p11111.png",   caption: "ನನ್ನ ಜಗತ್ತಿನ ಸ್ಪೆಷಲ್ ವ್ಯಕ್ತಿ ನೀನು 🫶" },
  { src: "photos/p22222.png",   caption: "From 2023 strangers to forever siblings 🫶" },
  { src: "photos/p101010.png",  caption: "ಅಕ್ಕ ಅಲ್ಲ… ನನ್ನ ಹ್ಯಾಪಿನೆಸ್ ❤️" },
  { src: "photos/p333333.png",   caption: "I found a sister where I least expected 🥹" },
  { src: "photos/13333.png",   caption: "ನೀನು ಬಂದ್ಮೇಲೆ ಜೀವನ ಚೆನ್ನಾಯಿತು 🥹" },
  { src: "photos/6.JPG",   caption: "I found a sister where I least expected 🥹" },
  { src: "photos/7.JPG",   caption: "Forever ನಿನ್ನ ತಮ್ಮ ❤️" },
  { src: "photos/8.JPG",   caption: "My happiness has a name — Lacchi 🤍" },
  { src: "photos/9.JPG",   caption: "ನಿನ್ನ ಜಾಗ ಯಾರಿಗೂ ಇಲ್ಲ 🤍" },
  { src: "photos/10.JPG",   caption: "She treats me like her own brother 🤗" },
  { src: "photos/11.JPG",   caption: "ನೀನು ನನ್ನ comfort person 🥹" },
  { src: "photos/12.JPG",   caption: "The best bonds happen unexpectedly ✨" },
  { src: "photos/13.JPG",   caption: "ಮಾತು ಬಿಡಬೇಡ ಅಕ್ಕ ❤️" },
  { src: "photos/14.jpg",   caption: "You understand my silence too 🥹" },
  { src: "photos/15.jpg",   caption: "ನನ್ನ ನಗುವಿನ ಕಾರಣ ನೀನು ✨" },
  { src: "photos/16.jpg",   caption: "One person, unlimited care ❤️" },
  { src: "photos/17.jpg",   caption: "ನೀನು ಸಿಕ್ಕಿದ್ದು ನನ್ನ luck 🫶" },
  { src: "photos/18.jpg",   caption: "Sister by bond, forever by heart 🫶" },
  { src: "photos/19.jpg",   caption: "ನನ್ನ ಜೀವನದ ಬೆಸ್ಟ್ ಗಿಫ್ಟ್ — ನೀನು ❤️" },
  { src: "photos/20.jpg",   caption: "Please stay till my last breath 🤍" },
  { src: "photos/21.jpg",   caption: "ನೀನು ನನ್ನ safe place 🥹" },
  { src: "photos/22.jpg",   caption: "You fixed parts of me you never broke 🥹" },
  { src: "photos/23.jpg",   caption: "ಅಕ್ಕ by heart ❤️" },
  { src: "photos/82.jpg",   caption: "My comfort person ❤️" },
  { src: "photos/83.jpg",   caption: "ನಿನ್ನ ಜೊತೆನೇ ಮನಸ್ಸಿಗೆ ಶಾಂತಿ 🤍" },
  { src: "photos/26.jpg",   caption: "I trust you more than anyone 🤗" },
  { src: "photos/27.jpg",   caption: "ನನ್ನ ಹೃದಯಕ್ಕೆ ಹತ್ತಿರದ ವ್ಯಕ್ತಿ ❤️" },
  { src: "photos/28.jpg",   caption: "Life got better after you entered it ✨" },
  { src: "photos/29.jpg",   caption: "ನೀನು ನನ್ನ ಲೋಕ ❤️" },
  { src: "photos/164.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಎರಡನೇ ಅಮ್ಮ ❤️" },
  { src: "photos/31.jpg",   caption: "ನನ್ನ smile ಹಿಂದೆ ನೀನು 🥹" },
  { src: "photos/32.jpg",   caption: "Not everyone gets a bond like this 🫶" },
  { src: "photos/33.jpg",   caption: "ನನ್ನ peace, ನನ್ನ akka 🤍" },
  { src: "photos/34.jpg",   caption: "If I made mistakes, scold me… but don’t leave me. 🥹" },
  { src: "photos/35.jpg",   caption: "ನಿನ್ನ ಜಾಗ ಶಾಶ್ವತ ❤️" },
  { src: "photos/36.jpg",   caption: "“You’re the reason my smile came back.” ❤️" },
  { src: "photos/37.jpg",   caption: "ನೀನು ಇದ್ದರೆ ಎಲ್ಲ ಚೆನ್ನಾಗಿದೆ 🫶" },
  { src: "photos/38.png",   caption: "“After meeting you, life felt lighter.” 🤍" },
  { src: "photos/39.jpg",   caption: "ನನ್ನ favorite notification — ನೀನು 🥹" },
  { src: "photos/40.jpg",   caption: "“No matter who comes, your place stays special.” ✨" },
  { src: "photos/41.jpg",   caption: "ನೀನು ನನ್ನ happiness ❤️" },
  { src: "photos/42.jpg",   caption: "“You are my favorite chapter.” 🫶" },
  { src: "photos/43.jpg",   caption: "ನನ್ನ ಮನಸ್ಸಿನ ಹತ್ತಿರ ನೀನು 🤍" },
  { src: "photos/44.jpg",   caption: "You’re not part of my life, you are my life 🤍" },
  { src: "photos/45.jpg",   caption: "ಅಕ್ಕ ಅಂತ ಕರೆಯೋದು ನನ್ನ luck 🥹" },
  { src: "photos/47.jpg",   caption: "Akka by choice, family by heart ❤️" },
  { src: "photos/48.jpg",   caption: "ನನ್ನ ದಿನದ best part — ನೀನು ❤️" },
  { src: "photos/50.jpg",   caption: "Some people become home 🫶" },
  { src: "photos/51.jpg",   caption: "ನೀನು ಮಾತಾಡಿದ್ರೆ ಸಾಕು 🫶" },
  { src: "photos/52.jpg",   caption: "You entered my life and changed everything ✨" },
  { src: "photos/53.jpg",   caption: "ನಿನ್ನ care ತುಂಬಾ special ❤️" },
  { src: "photos/54.jpg",   caption: "My heart feels safe with you 🥹" },
  { src: "photos/55.jpg",   caption: "ನೀನು ಬೇರೆ level akka 🤍" },
  { src: "photos/56.jpg",   caption: "You’re my peace in a noisy world 🤗" },
  { src: "photos/57.jpg",   caption: "ನನ್ನ heart ಗೆ close ಇರುವವಳು ❤️" },
  { src: "photos/58.jpg",   caption: "I didn’t expect you, but I needed you ❤️" },
  { src: "photos/59.jpg",   caption: "ನೀನು ಸಿಕ್ಕಿದ್ದು blessing 🥹" },
  { src: "photos/60.jpg",   caption: "Lucky to have a sister like you 🫶" },
  { src: "photos/61.jpg",   caption: "ನನ್ನ favorite chapter — ನೀನು 🫶" },
  { src: "photos/62.jpg",   caption: "One bond, countless memories ✨" },
  { src: "photos/63.jpg",   caption: "ಮಾತು ಬಿಡಬೇಡ ಅಕ್ಕ ❤️" },
  { src: "photos/64.jpg",   caption: "My favorite notification is yours 🥹" },
  { src: "photos/65.jpg",   caption: "ನೀನು ಇಲ್ಲ ಅಂದ್ರೆ ಏನೋ missing 🥹" },
  { src: "photos/66.jpg",   caption: "You are my daily happiness ❤️" },
  { src: "photos/67.jpg",   caption: "Forever ನೀನೇ special ❤️" },
  { src: "photos/68.jpg",   caption: "My person. My akka. My comfort 🤍" },
  { src: "photos/69.jpg",   caption: "ನನ್ನ ಟ್ರಸ್ಟ್ ಶುರು ಆಗೋದು ನಿನ್ನಿಂದ 🤍" },
  { src: "photos/70.jpg",   caption: "You’re my strongest support system 🤗" },
  { src: "photos/71.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಜೀವನ ಅರ್ಧ ಸಮಸ್ಯೆ ಕಡಿಮೆ 🥹" },
  { src: "photos/72.jpg",   caption: "The best thing 2024 gave me — you ❤️" },
  { src: "photos/73.jpg",   caption: "ಅಕ್ಕನ ಪ್ರೀತಿ ಬೇರೆ level ❤️" },
  { src: "photos/74.jpg",   caption: "My bond with you > everything ✨" },
  { src: "photos/75.jpg",   caption: "ಜಗಳ ಜಾಸ್ತಿ… ಪ್ರೀತಿ ಇನ್ನೂ ಜಾಸ್ತಿ 🤗" },
  { src: "photos/76.jpg",   caption: "I smile differently because of you 🥹" },
  { src: "photos/77.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಮನೆಗೆ ಬೇರೆ ಖುಷಿ ❤️" },
  { src: "photos/78.jpg",   caption: "You’re my permanent favorite ❤️" },
  { src: "photos/79.jpg",   caption: "ನನ್ನ ಮೊದಲ best friend — ನನ್ನ ಅಕ್ಕ 🫶" },
  { src: "photos/80.jpg",   caption: "One call from you fixes my mood 🤍" },
  { src: "photos/81.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ care + love + support ❤️" },
  { src: "photos/82.jpg",   caption: "You’re my happy place 🤗" },
  { src: "photos/83.jpg",   caption: "ನನ್ನ strength — ನನ್ನ ಅಕ್ಕ 🥹" },
  { src: "photos/84.jpg",   caption: "Thank you for treating me like your own brother ❤️" },
  { src: "photos/85.jpg",   caption: "ಅಕ್ಕನ ಬೈಗುಳದಲ್ಲೂ ಪ್ರೀತಿ ಇರುತ್ತೆ 😄❤️" },
  { src: "photos/86.jpg",   caption: "I don’t want many people, I just want you around 🥹" },
  { src: "photos/87.jpg",   caption: "ಎಲ್ಲರಿಗೂ ಅಕ್ಕ ಇರುತ್ತಾರೆ, ನನ್ನಂಥ ಅಕ್ಕ ಎಲ್ಲರಿಗೂ ಇರಲ್ಲ 🫶" },
  { src: "photos/88.jpg",   caption: "You became special without even trying ✨" },
  { src: "photos/89.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಚಿಕ್ಕ ಚಿಕ್ಕ ಸಂತೋಷಗಳ ದೊಡ್ಡ ಕಾರಣ ❤️" },
  { src: "photos/90.jpg",   caption: "Some bonds don’t need explanations 🫶" },
  { src: "photos/91.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಯಾವ tension ಕೂಡ tension ಅನಿಸಲ್ಲ 🥹" },
  { src: "photos/92.jpg",   caption: "Sister by heart, not by blood ❤️" },
  { src: "photos/93.jpg",   caption: "ಸಿಸ್ಟರ್ ಅಲ್ಲ… ನನ್ನ superhero ❤️" },
  { src: "photos/94.jpg",   caption: "Forever my Angel ◈" },
  { src: "photos/95.jpg",   caption: "ಅಕ್ಕ ಜೊತೆ ಜಗಳ ದಿನವೂ… ಮಾತು ಬಿಡೋದು never 😄" },
  { src: "photos/96.jpg",   caption: "Forever my Pretty Angel Akka 🥹" },
  { src: "photos/97.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಮನೆಯ peace 🤍" },
  { src: "photos/98.jpg",   caption: "You’re the chapter I never want to end 🤍" },
  { src: "photos/99.jpg",   caption: "ಜೀವನದಲ್ಲಿ ಬೆಸ್ಟ್ gift — ಅಕ್ಕ ❤️" },
  { src: "photos/100.jpg",   caption: "Your care means the world to me ❤️" },
  { src: "photos/101.jpg",   caption: "ಅಕ್ಕನ ಪ್ರೀತಿ explain ಮಾಡೋಕೆ words ಸಾಲಲ್ಲ 🥹" },
  { src: "photos/102.jpg",   caption: "My trust starts with you 🤗" },
  { src: "photos/103.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಮನಸ್ಸಿಗೆ ಧೈರ್ಯ ❤️" },
  { src: "photos/104.jpg",   caption: "You understand me without words 🥹" },
  { src: "photos/105.jpg",   caption: "Forever my favorite akka 🤗" },
  { src: "photos/106.jpg",   caption: "Stay with me forever, akka ❤️" },
  { src: "photos/107.jpg",   caption: "ಅಕ್ಕ = love in another form ❤️" },
  { src: "photos/108.jpg",   caption: "Every memory with you is precious ✨" },
  { src: "photos/109.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಧೈರ್ಯ ತಾನಾಗೇ ಬರುತ್ತೆ ❤️" },
  { src: "photos/110.jpg",   caption: "You made life brighter 🤍" },
  { src: "photos/111.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಪ್ರೀತಿಯ ಮತ್ತೊಂದು ಹೆಸರು 🥹" },
  { src: "photos/112.jpg",   caption: "My comfort zone has your name ❤️" },
  { src: "photos/113.jpg",   caption: "ಅಕ್ಕನ ಕಾಳಜಿ ಯಾವಾಗಲೂ ಸ್ಪೆಷಲ್ ❤️" },
  { src: "photos/114.jpg",   caption: "Even bad days feel lighter with you 🥹" },
  { src: "photos/115.jpg",   caption: "ಅಕ್ಕ ಜೊತೆ ಜಗಳ common… ಪ್ರೀತಿ permanent 😄❤️" },
  { src: "photos/116.jpg",   caption: "My favorite human, always 🤗" },
  { src: "photos/117.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಜೀವನ ಸ್ವಲ್ಪ easy ಆಗುತ್ತೆ 🫶" },
  { src: "photos/118.jpg",   caption: "Beat me, scold me… but don’t leave me akka 🥹" },
  { src: "photos/119.jpg",   caption: "ಅಕ್ಕನ ಪ್ರೀತಿ silent ಆಗಿರುತ್ತೆ… ಆದ್ರೆ real ಆಗಿರುತ್ತೆ ❤️" },
  { src: "photos/120.jpg",   caption: "Stay with me till my last breath ❤️" },
  { src: "photos/121.jpg",   caption: "ನನ್ನ secret keeper — ನನ್ನ ಅಕ್ಕ 🤫❤️" },
  { src: "photos/122.jpg",   caption: "Evan yavanu idhella heltidane antha andkobeda 😁" },
  { src: "photos/123.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಯಾವಾಗಲೂ side ನಿಲ್ಲೋ ವ್ಯಕ್ತಿ 🥹" },
  { src: "photos/124.jpg",   caption: "I trust you more than anyone else 🤍" },
  { src: "photos/125.jpg",   caption: "ಮನೆಯ ನಿಜವಾದ support system — ಅಕ್ಕ ❤️" },
  { src: "photos/126.jpg",   caption: "After meeting you, I started smiling more ❤️" },
  { src: "photos/127.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಒಂಟಿತನ ಕಡಿಮೆ ಆಗುತ್ತೆ 🤍" },
  { src: "photos/128.jpg",   caption: "You came into my life and healed things silently 🥹" },
  { src: "photos/129.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಯಾವಾಗಲೂ caring mode ❤️" },
  { src: "photos/130.jpg",   caption: "No replacement. No comparison. Only you ✨" },
  { src: "photos/131.jpg",   caption: "ಅಕ್ಕನ ಜೊತೆ memories ಯಾವಾಗಲೂ special 🥹" },
  { src: "photos/132.jpg",   caption: "You’re not a habit, you’re a blessing ❤️" },
  { src: "photos/133.jpg",   caption: "ಒಂದು ಅಕ್ಕ ಇದ್ದರೆ ಸಾಕು, ಜೀವನ colorfull ❤️" },
  { src: "photos/134.jpg",   caption: "Forever your little brother 🤗" },
  { src: "photos/135.jpg",   caption: "ಅಕ್ಕನ love ಬೇರೆ level ✨" },
  { src: "photos/136.jpg",   caption: "My world became better after you 🌍❤️" },
  { src: "photos/137.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಮನೆಯ vibe ಬೇರೆ ❤️" },
  { src: "photos/138.jpg",   caption: "An elder sister is a little bit of childhood that never leaves us. ❤️" },
  { src: "photos/139.jpg",   caption: "ನನ್ನ ಮೊದಲ teacher — ನನ್ನ ಅಕ್ಕ 🥹" },
  { src: "photos/140.jpg",   caption: "My akka: part sister, part best friend, part second mom. 🫶" },
  { src: "photos/141.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ half friend, half mother ❤️" },
  { src: "photos/142.jpg",   caption: "Behind every strong sibling bond is an amazing elder sister. ❤️" },
  { src: "photos/143.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಯಾವಾಗಲೂ backup ಇರುತ್ತೆ 😄" },
  { src: "photos/144.jpg",   caption: "An akka’s care hits differently. 🥹" },
  { src: "photos/145.jpg",   caption: "ನನ್ನ biggest supporter — ನನ್ನ ಅಕ್ಕ ❤️"},
  { src: "photos/146.jpg",   caption: "No one supports like an elder sister. 🤍" },
  { src: "photos/147.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ forever safe place 🫶" },
  { src: "photos/148.jpg",   caption: "A sister’s love stays, even when words don’t. ❤️" },
  { src: "photos/149.jpg",   caption: "ಅಕ್ಕನ smile ನೋಡಿದ್ರೆ ದಿನ ಚೆನ್ನಾಗುತ್ತೆ 🥹" },
  { src: "photos/150.jpg",   caption: "Akka — my forever safe place. 🫶" },
  { src: "photos/151.jpg",   caption: "ಸಣ್ಣ ಜಗಳ, ದೊಡ್ಡ ಪ್ರೀತಿ — ಅಕ್ಕ ಜೊತೆ ❤️" },
  { src: "photos/152.jpg",   caption: "An elder sister is life’s first protector. ❤️" },
  { src: "photos/153.jpg",   caption: "ಅಕ್ಕನ ಬೈಗುಳವೂ caring version 😄❤️" },
  { src: "photos/154.jpg",   caption: "An elder sister is the first person who protects you without being asked. ❤️" },
  { src: "photos/155.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ಮನೆಗೆ extra happiness ❤️" },
  { src: "photos/156.jpg",   caption: "A sister may annoy you daily, but she’ll still stand by you forever. 🫶" },
  { src: "photos/157.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ life ಗೆ balance ಇರುತ್ತೆ 🥹" },
  { src: "photos/158.jpg",   caption: "Big sisters don’t let you fall alone. ❤️" },
  { src: "photos/159.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ forever support ❤️" },
  { src: "photos/160.jpg",   caption: "A sister’s place can never be replaced. ❤️" },
  { src: "photos/161.jpg",   caption: "ಅಕ್ಕನ ಜೊತೆ bond ಬೇರೆ level ❤️" },
  { src: "photos/162.jpg",   caption: "Blessed with the best akka. 🤍" },
  { src: "photos/163.jpg",   caption: "ಜಗಳ ಮಾಡ್ತೀವಿ… ಆದ್ರೆ ಇರೋದು ಜೊತೆಯಲ್ಲೇ 🥹" },
  { src: "photos/164.jpg",   caption: "Life feels safer when you have an akka beside you. 🤍" },
  { src: "photos/165.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ tension ಅರ್ಧ ಆಗುತ್ತೆ ❤️" },
  { src: "photos/166.jpg",   caption: "Akka, life feels better with you in it. 🤍" },
  { src: "photos/167.jpg",   caption: "ನನ್ನ happiness‌ನ ಒಂದು ಭಾಗ — ಅಕ್ಕ 🤍"},
  { src: "photos/168.jpg",   caption: "You’re not just my sister, you’re my comfort person. ❤️" },
  { src: "photos/169.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ trust ❤️" },
  { src: "photos/170.jpg",   caption: "No matter what happens, your place in my life will always stay special. 🫶" },
  { src: "photos/171.jpg",   caption: "ನನ್ನ life partner ಅಲ್ಲ… life supporter — ಅಕ್ಕ 🥹" },
  { src: "photos/172.jpg",   caption: "Akka, thank you for always being there for me. 🥹" },
  { src: "photos/173.jpg",   caption: "ಅಕ್ಕ ಜೊತೆ ಇರುವ memories priceless ❤️" },
  { src: "photos/174.jpg",   caption: "You make my worst days feel a little easier. ❤️" },
  { src: "photos/175.jpg",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ silent strength 🤍" },
  { src: "photos/176.png",   caption: "I’m lucky that life gave me a sister like you. 🤍" },
  { src: "photos/177.png",   caption: "ನನ್ನ smileಗೆ ಕಾರಣಗಳಲ್ಲಿ ಒಬ್ಬಳು — ಅಕ್ಕ ❤️" },
  { src: "photos/178.png",   caption: "You understand me in ways I can’t explain. ❤️" },
  { src: "photos/179.png",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಯಾವಾಗಲೂ home feeling 🥹" },
  { src: "photos/180.png",   caption: "Akka, your care means more than you know. 🥹" },
  { src: "photos/181.png",   caption: "ಅಕ್ಕನ care ಯಾವಾಗಲೂ extra ❤️" },
  { src: "photos/182.png",   caption: "You’re my favorite person to annoy and my favorite person to trust. 😄❤️" },
  { src: "photos/183.png",   caption: "ನನ್ನ biggest blessing — ಅಕ್ಕ 🤍" },
  { src: "photos/184.png",   caption: "I don’t need many people; having you is enough. 🤍" },
  { src: "photos/185.png",   caption: "ಅಕ್ಕ ಅಂದ್ರೆ ದಿನದ peace ❤️" },
  { src: "photos/186.png",   caption: "Akka, your presence itself gives me peace. ❤️" },
  { src: "photos/187.png",   caption: "ಒಂದು ಅಕ್ಕ ಸಾಕು… life happy ಆಗೋಕೆ 🥹" },
  { src: "photos/188.png",   caption: "No replacement, no comparison — only you. 🥹" },
  { src: "photos/189.png",   caption: "ಅಕ್ಕ ಜೊತೆಗಿನ bond explain ಮಾಡೋಕೆ words ಸಾಲಲ್ಲ ❤️" },
  { src: "photos/190.png",   caption: "Whatever happens, stay with me forever, akka. ❤️" },
  { src: "photos/p2.png",   caption: "Forever grateful for my akka 🫶" },
  { src: "photos/192.jpg",   caption: "You came into my life and made it brighter. 🤍" },
  { src: "photos/195.jpg",   caption: "ಅಕ್ಕ ಇದ್ದರೆ ಜೀವನಕ್ಕೆ strength ಬರುತ್ತೆ ❤️" },
  { src: "photos/196.jpg",   caption: "My happiness has your name in it, akka. 🫶" },
  { src: "photos/197.jpg",   caption: "ಅಕ್ಕ = love + care + madness 😄❤️" },
  { src: "photos/198.jpg",   caption: "You’re not my sister by blood, but by heart. ❤️" },
  { src: "photos/1.png",   caption: "ಎಲ್ಲರಿಗೂ sister ಇರುತ್ತಾರೆ… ನನ್ನದು akka ❤️" },
  { src: "photos/2.png",   caption: "You’ll always have a special place in my life. 🥹" },
  { src: "photos/3.png",   caption: "ಅಕ್ಕನ ಸ್ಥಾನ ಯಾರೂ ತುಂಬೋಕಾಗಲ್ಲ 🥹" },
  { src: "photos/4.webp",   caption: "Forever your little brother, akka. ❤️" },
  { src: "photos/5.png",   caption: "ನನ್ನ favorite person — ಅಕ್ಕ ❤️" },
  { src: "photos/p2.png",   caption: "I’m lucky that life gave me a sister like you. 🤍" },
  { src: "photos/p111.png",   caption: "ಅಕ್ಕ ಇದ್ದರೆ life ಸ್ವಲ್ಪ beautiful 🤍" },
  { src: "photos/p222.png",   caption: "You’re my favorite person to annoy and my favorite person to trust. 😄❤️" },

  // ✏️ Just keep adding lines below — no limit!
  // { src: "photos/newphoto.png", caption: "Your caption here" },
];